identifier: 'test'
note: ''

# GENERAL ENVIRONMENT SETTINGS
actions_file: 'Learning_To_Adapt/SafeRL_WMPC/_parameters/test.csv'
n_mpc_steps: 20
max_lat_dev: 2.0
episode_length: 128    
n_environments: 16
n_eval_episodes: 1
n_envs_eval: 1
evaluation_frequency: 1_000

# TRAINING SETTINGS
n_training_steps: 1_500_000
use_adaptive_learning_rate: true
learning_rate: 0.004                  # NOTE: only active without adaptive learning rate 
adaptive_lr_final: 0.0001
adaptive_lr_init: 0.005
adaptive_lr_decay: 0.4
n_steps: 512
batch_size: 4096
n_epochs: 5
clip_range: 0.2
ent_coef: 0.006
gae_lambda: 0.98
gamma: 0.8
max_grad_norm: 0.5
vf_coef: 0.5
net_arch: [128, 256, 128]

# REWARD SETTINGS
rew_sigmas:       [0.1, 0.5]          # reward bell width
rew_lims_lat_dev: [0.0, 0.4]          # normalization limits lateral deviation
rew_lims_vel_dev: [0.0, 1.0]          # normalization limits velocity deviation

# OBSERVATION SETTINGS
obs_anticipation_horizon: 38          # furthest reference point to be sampled
obs_n_anticipation_points: 10          # number of sample points
n_obs_stack: 1                        # observation stack length