costfunction_type: 'NONLINEAR_LS' # 'NONLINEAR_LS' or 'EXTERNAL'
solver_build: True
solver_generate_C_code: True


enable_WMPC: True          # Weights-varying MPC (COMING-SOON) CAUTION: must be disabled for WMPC training
WMPC_model: 'Learning_To_Adapt/SafeRL_WMPC/_models/test'
weights_update_period: 20   # number of MPC steps to run between weight updates

## Static cost function parameters optimized with Multiobjective Bayesian Optimization
s_lon           : 1
s_lat           : 1
s_yaw           : 1
s_vel           : 1
s_jerk          : 1
s_steering_rate : 1

q_lon           : 2.8
q_lat           : 2.8
q_yaw           : 0.4
q_vel           : 0.2
r_jerk          : 38.1
r_steering_rate : 101.4
L1_pen          : 106.7
L2_pen          : 9.9

# --- constraints params
lookuptable_gg_limits: 'EDGAR/ggv.csv'
combined_acc_limits: 2
  # 0: no combined limits (separate limits)
  # 1: Diamond shaped combined lat lon acceleration limits
  # 2: Circle shaped combined lat lon acceleration limits

## --- RNMPC & SNMPC specific parameters for Polynomial Chaos Expansion (PCE) ---
stds:   # assumed disturbance ranges
 - 0.0   # w_pos_x
 - 0.0   # w_pos_y
 - 0.0   # w_yaw
 - 0.8   # w_vlong
 - 0.35   # w_vlat 
 - 0.035  # w_yawrate 
 - 0.0   # w_delta_f
 - 0.0   # w_a
uncertainty_propagation_horizon: 5

## --- SNMPC specific parameters for PCE ---
n_samples: 10  # number of collocation points
gamma: 0.8
expansion_degree: 2
disturbance_type: 'gaussian'
