#vehicle params:
l: 0.324
lf: 0.162
lr: 0.162
m: 3.9
Iz: 0.128
h: 0.045
ro: 1.225
S: 0.05
Cd: 0.9
veh_length: 0.568
veh_width: 0.296
veh_height: 0.2

#constraints:
jerk_min: -20.0
jerk_max: 20.0
lat_acc_min: -5.886
lat_acc_max: 5.886
acc_min: -4.5
acc_max: 3.0
delta_f_min: -0.44
delta_f_max: 0.44
delta_f_dot_min: -4.4
delta_f_dot_max: 4.4
